// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb8_Tx8kGztPvU6SSTc1yesbQwIzQvuUM',
    appId: '1:472441506735:web:ffbe305dc660bce2857d5a',
    messagingSenderId: '472441506735',
    projectId: 'filespace-db4e7',
    authDomain: 'filespace-db4e7.firebaseapp.com',
    databaseURL: 'https://filespace-db4e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'filespace-db4e7.appspot.com',
    measurementId: 'G-F4M3RDGV5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTkSgzzHz6-bKMns6rIx8ynQWP7SdKLs',
    appId: '1:472441506735:android:68c9f34a6a3f413c857d5a',
    messagingSenderId: '472441506735',
    projectId: 'filespace-db4e7',
    databaseURL: 'https://filespace-db4e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'filespace-db4e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHUWmF43nmrX5yjuXR1A4E68YcFF0QW0',
    appId: '1:472441506735:ios:f7b9793d32d83ce3857d5a',
    messagingSenderId: '472441506735',
    projectId: 'filespace-db4e7',
    databaseURL: 'https://filespace-db4e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'filespace-db4e7.appspot.com',
    iosClientId: '472441506735-tt9mreuns39nf6om0dj7qh8nat0fphed.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientApp',
  );
}
